validator = true

[node]
name = "catalyst-node"
private_key_file = "node.key"
auto_generate_identity = true

[network]
listen_addresses = ["/ip4/0.0.0.0/tcp/30333"]
bootstrap_peers = []
max_peers = 50
min_peers = 5

[storage]
data_dir = "data"
enabled = true
capacity_gb = 10

[consensus]
cycle_duration_seconds = 60
max_transactions_per_block = 1000
min_producer_count = 1
max_producer_count = 100

[rpc]
enabled = true
address = "127.0.0.1"
port = 9933
cors_enabled = true
cors_origins = ["*"]

[service_bus]
enabled = false
websocket_port = 8546
max_connections = 1000

[dfs]
enabled = false
cache_dir = "dfs_cache"
cache_size_gb = 5

[logging]
level = "info"
format = "text"
file_enabled = true
file_path = "logs/catalyst.log"
console_enabled = true
