name: Public testnet readiness
description: Track a concrete improvement required for stable public testnet operation.
title: "[Testnet] <short description>"
labels: ["testnet"]
body:
  - type: markdown
    attributes:
      value: |
        Use this for work items that are required to run a stable public test network.
        If it is spec-driven, also link the relevant spec sections.

  - type: input
    id: milestone
    attributes:
      label: Milestone
      description: Example: "Milestone B — Transaction pipeline"
      placeholder: "Milestone <A–G> — <name>"
    validations:
      required: true

  - type: input
    id: spec_ref
    attributes:
      label: Spec reference (optional but preferred)
      placeholder: "Consensus v1.2 §X.Y (p.ZZ–ZZ)"
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Concrete, testable outcomes (include failure modes).
    validations:
      required: true

  - type: textarea
    id: runbook
    attributes:
      label: Runbook impact
      description: What changes for operators? ports/config steps/log locations/etc.
    validations:
      required: false

  - type: textarea
    id: validation
    attributes:
      label: Validation
      description: How do we verify this in local testnet/devnet and in public testnet?
      value: |
        - [ ] Local: `make smoke-testnet`
        - [ ] Local: `make testnet-up && make testnet-basic-test`
        - [ ] Public: join from a clean machine and reach same head/state root
    validations:
      required: true

