name: Spec implementation ticket
description: Implement a spec-referenced capability with clear acceptance criteria and tests.
title: "[Spec] <short description>"
labels: ["spec"]
body:
  - type: markdown
    attributes:
      value: |
        Please tie this work item to the authoritative PDFs:
        - Consensus v1.2: https://catalystnet.org/media/CatalystConsensusPaper.pdf
        - Network intro: https://catalystnet.org/media/IntroductionToCatalystNetwork.pdf

  - type: input
    id: spec_ref
    attributes:
      label: Spec reference (section/page)
      description: Example: "Consensus paper v1.2 §4.5 (Transaction validity), p.32–33"
      placeholder: "Consensus v1.2 §X.Y (p.ZZ–ZZ)"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What is missing/incorrect today?
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope (in/out)
      description: Be explicit about what is included and what is deferred.
      value: |
        In:
        - 

        Out:
        - 
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Concrete, testable outcomes (prefer bullet points).
    validations:
      required: true

  - type: textarea
    id: test_plan
    attributes:
      label: Test plan
      description: Unit/integration/smoke tests to add or update (and how to run them).
      value: |
        - [ ] Unit test(s):
        - [ ] Integration/testnet validation:
    validations:
      required: true

  - type: textarea
    id: code_areas
    attributes:
      label: Code areas (expected)
      description: Files/crates likely to change.
      value: |
        - crates/catalyst-core/...
        - crates/catalyst-consensus/...
        - crates/catalyst-cli/...
        - crates/catalyst-rpc/...
    validations:
      required: false

  - type: textarea
    id: deps
    attributes:
      label: Dependencies / sequencing
      description: Other issues that must land first; include links.
    validations:
      required: false

